package agents

import (
	"bufio"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// scriptedInterviewer returns answers from a fixed list, one per Ask call.
type scriptedInterviewer struct {
	answers []string
	calls   int
}

func (s *scriptedInterviewer) Ask(prompt string) (string, error) {
	if s.calls >= len(s.answers) {
		return "", nil
	}
	ans := s.answers[s.calls]
	s.calls++
	return ans, nil
}

func TestCharterAskAllRequiresNonOptionalFields(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"", "users", "latency", "out", ""},
	}}
	_, err := c.askAll()
	if err == nil {
		t.Fatal("expected error on empty purpose")
	}
	if !strings.Contains(err.Error(), "purpose") {
		t.Errorf("error should mention 'purpose', got %v", err)
	}
}

func TestCharterAskAllAcceptsEmptyOverrides(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"a tool", "developers", "correctness", "talking", ""},
	}}
	answers, err := c.askAll()
	if err != nil {
		t.Fatal(err)
	}
	if answers["purpose"] != "a tool" {
		t.Errorf("purpose = %q", answers["purpose"])
	}
	if answers["overrides"] != "" {
		t.Errorf("overrides should be empty, got %q", answers["overrides"])
	}
}

func TestCharterAskAllHandlesAllFiveFields(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"p", "u", "c", "o", "ov"},
	}}
	answers, err := c.askAll()
	if err != nil {
		t.Fatal(err)
	}
	if len(answers) != 5 {
		t.Errorf("got %d answers, want 5", len(answers))
	}
	for _, k := range []string{"purpose", "users", "constraint", "out_of_scope", "overrides"} {
		if _, ok := answers[k]; !ok {
			t.Errorf("missing key %q in answers", k)
		}
	}
}

func TestCharterWriteCreatesAidevDirAndFile(t *testing.T) {
	dir := t.TempDir()
	c := &Charter{}
	body := "# Charter\n\n## Purpose\nA test.\n"
	path, err := c.writeCharter(dir, body)
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "charter.md" {
		t.Errorf("basename = %q", filepath.Base(path))
	}
	if filepath.Dir(path) != filepath.Join(dir, ".aidev") {
		t.Errorf("parent dir = %q", filepath.Dir(path))
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "# Charter") {
		t.Error("charter missing header")
	}
	if !strings.Contains(string(data), "Generated by aidev") {
		t.Error("charter missing footer stamp")
	}
}

func TestFirstLine(t *testing.T) {
	if firstLine("abc\ndef") != "abc" {
		t.Errorf("firstLine wrong: %q", firstLine("abc\ndef"))
	}
	if firstLine("no newline") != "no newline" {
		t.Errorf("firstLine wrong: %q", firstLine("no newline"))
	}
	if firstLine("") != "" {
		t.Errorf("firstLine wrong: %q", firstLine(""))
	}
}

func TestCharterQuestionsCoverAllExpectedKeys(t *testing.T) {
	want := map[string]bool{
		"purpose":      true,
		"users":        true,
		"constraint":   true,
		"out_of_scope": true,
		"overrides":    true,
	}
	for _, q := range CharterQuestions {
		if !want[q.Key] {
			t.Errorf("unexpected question key: %q", q.Key)
		}
		delete(want, q.Key)
	}
	for k := range want {
		t.Errorf("missing question key: %q", k)
	}
}

// TestRunWithAnswersRejectsMissingFields ensures the non-interactive
// path validates required answers BEFORE hitting the LLM. We can't
// test the happy path without a real Provider, so this test only
// covers the validation branch: each case is expected to error
// during validation and never reach `synthesise`.
func TestRunWithAnswersRejectsMissingFields(t *testing.T) {
	cases := []struct {
		name    string
		answers map[string]string
	}{
		{
			name: "missing purpose",
			answers: map[string]string{
				"users":        "devs",
				"constraint":   "correctness",
				"out_of_scope": "web ui",
			},
		},
		{
			name: "whitespace-only users",
			answers: map[string]string{
				"purpose":      "a tool",
				"users":        "   ",
				"constraint":   "correctness",
				"out_of_scope": "web ui",
			},
		},
		{
			name: "missing constraint",
			answers: map[string]string{
				"purpose":      "a tool",
				"users":        "devs",
				"out_of_scope": "web ui",
			},
		},
		{
			name: "missing out_of_scope",
			answers: map[string]string{
				"purpose":    "a tool",
				"users":      "devs",
				"constraint": "correctness",
			},
		},
		{
			name:    "nil map",
			answers: nil,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			// Provider is nil — validation must catch the missing
			// field and return an error BEFORE the synthesise call
			// would dereference Provider. A nil-pointer panic here
			// means validation is wrong.
			c := &Charter{Provider: nil}
			_, err := c.RunWithAnswers(context.Background(), "/tmp/any", tc.answers)
			if err == nil {
				t.Error("expected validation error, got nil")
			}
		})
	}
}

// TestRunWithAnswersOptionalOverridesDoesNotValidate ensures the
// `overrides` field is allowed to be empty — it's the single optional
// field in the question set.
func TestRunWithAnswersAllowsEmptyOverrides(t *testing.T) {
	// Can't reach the LLM path with a nil Provider, so we only
	// check that the 'overrides is optional' rule is encoded in
	// validation by verifying a map with every required field
	// present + overrides missing does NOT fail at validation (it
	// fails later at synthesise with a different error). A panic
	// from nil-provider dereference would also satisfy this — but
	// we defend against that by recovering and checking the
	// recovery reason doesn't mention "is required".
	defer func() {
		if r := recover(); r != nil {
			// Expected: synthesise dereferences the nil Provider.
			// That's fine — it means we got past validation.
			msg := toString(r)
			if strings.Contains(msg, "is required") {
				t.Errorf("validation error leaked into panic: %v", r)
			}
		}
	}()
	c := &Charter{Provider: nil}
	_, _ = c.RunWithAnswers(context.Background(), "/tmp/any", map[string]string{
		"purpose":      "a tool",
		"users":        "devs",
		"constraint":   "correctness",
		"out_of_scope": "web ui",
	})
}

func toString(v interface{}) string {
	switch x := v.(type) {
	case string:
		return x
	case error:
		return x.Error()
	default:
		return ""
	}
}

// lineReadingInterviewer is a minimal Interviewer that reads from an
// arbitrary io.Reader (not os.Stdin), so we can unit-test multi-word
// answer handling without needing a real TTY. It mirrors the
// line-reading logic in StdinInterviewer but skips the TTY check.
type lineReadingInterviewer struct {
	reader *bufio.Reader
}

func (l *lineReadingInterviewer) Ask(prompt string) (string, error) {
	line, err := l.reader.ReadString('\n')
	if err != nil && err.Error() != "EOF" {
		return "", err
	}
	return strings.TrimRight(line, "\r\n"), nil
}

// TestInterviewerReadsWholeMultiWordLines is the regression test for
// the Fscanln bug — StdinInterviewer used to read only the first
// whitespace-delimited token of a multi-word answer, pushing the rest
// of the sentence into the next question. The fix is to read a whole
// line via bufio.Reader. This test drives the fixed implementation
// with a canned multi-question transcript.
func TestInterviewerReadsWholeMultiWordLines(t *testing.T) {
	transcript := "AiSU is a data governance and access tool\n" +
		"Business executives and professionals\n" +
		"correctness\n" +
		"web UI, any public-facing consumer product\n" +
		"\n"
	interviewer := &lineReadingInterviewer{reader: bufio.NewReader(strings.NewReader(transcript))}
	c := &Charter{Interviewer: interviewer}
	answers, err := c.askAll()
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"purpose":      "AiSU is a data governance and access tool",
		"users":        "Business executives and professionals",
		"constraint":   "correctness",
		"out_of_scope": "web UI, any public-facing consumer product",
		"overrides":    "",
	}
	for k, v := range want {
		if answers[k] != v {
			t.Errorf("answer[%q] = %q, want %q", k, answers[k], v)
		}
	}
}
