package agents

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// scriptedInterviewer returns answers from a fixed list, one per Ask call.
type scriptedInterviewer struct {
	answers []string
	calls   int
}

func (s *scriptedInterviewer) Ask(prompt string) (string, error) {
	if s.calls >= len(s.answers) {
		return "", nil
	}
	ans := s.answers[s.calls]
	s.calls++
	return ans, nil
}

func TestCharterAskAllRequiresNonOptionalFields(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"", "users", "latency", "out", ""},
	}}
	_, err := c.askAll()
	if err == nil {
		t.Fatal("expected error on empty purpose")
	}
	if !strings.Contains(err.Error(), "purpose") {
		t.Errorf("error should mention 'purpose', got %v", err)
	}
}

func TestCharterAskAllAcceptsEmptyOverrides(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"a tool", "developers", "correctness", "talking", ""},
	}}
	answers, err := c.askAll()
	if err != nil {
		t.Fatal(err)
	}
	if answers["purpose"] != "a tool" {
		t.Errorf("purpose = %q", answers["purpose"])
	}
	if answers["overrides"] != "" {
		t.Errorf("overrides should be empty, got %q", answers["overrides"])
	}
}

func TestCharterAskAllHandlesAllFiveFields(t *testing.T) {
	c := &Charter{Interviewer: &scriptedInterviewer{
		answers: []string{"p", "u", "c", "o", "ov"},
	}}
	answers, err := c.askAll()
	if err != nil {
		t.Fatal(err)
	}
	if len(answers) != 5 {
		t.Errorf("got %d answers, want 5", len(answers))
	}
	for _, k := range []string{"purpose", "users", "constraint", "out_of_scope", "overrides"} {
		if _, ok := answers[k]; !ok {
			t.Errorf("missing key %q in answers", k)
		}
	}
}

func TestCharterWriteCreatesAidevDirAndFile(t *testing.T) {
	dir := t.TempDir()
	c := &Charter{}
	body := "# Charter\n\n## Purpose\nA test.\n"
	path, err := c.writeCharter(dir, body)
	if err != nil {
		t.Fatal(err)
	}
	if filepath.Base(path) != "charter.md" {
		t.Errorf("basename = %q", filepath.Base(path))
	}
	if filepath.Dir(path) != filepath.Join(dir, ".aidev") {
		t.Errorf("parent dir = %q", filepath.Dir(path))
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "# Charter") {
		t.Error("charter missing header")
	}
	if !strings.Contains(string(data), "Generated by aidev") {
		t.Error("charter missing footer stamp")
	}
}

func TestFirstLine(t *testing.T) {
	if firstLine("abc\ndef") != "abc" {
		t.Errorf("firstLine wrong: %q", firstLine("abc\ndef"))
	}
	if firstLine("no newline") != "no newline" {
		t.Errorf("firstLine wrong: %q", firstLine("no newline"))
	}
	if firstLine("") != "" {
		t.Errorf("firstLine wrong: %q", firstLine(""))
	}
}

func TestCharterQuestionsCoverAllExpectedKeys(t *testing.T) {
	want := map[string]bool{
		"purpose":      true,
		"users":        true,
		"constraint":   true,
		"out_of_scope": true,
		"overrides":    true,
	}
	for _, q := range CharterQuestions {
		if !want[q.Key] {
			t.Errorf("unexpected question key: %q", q.Key)
		}
		delete(want, q.Key)
	}
	for k := range want {
		t.Errorf("missing question key: %q", k)
	}
}
