package agents

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleFollowUpsFile = `# Follow-up issues proposed by the Reviewer

_Generated by aidev on 2026-04-13. Review these, then file manually or wait for ` + "`aidev followups --file-issues`" + ` in a future release._

## 1. Refactor oldPkg/legacy.go

labels: tech-debt, refactor

200-line function the new code touches indirectly. Worth extracting to a package-private helper so the diff the Implementer produced doesn't accumulate more complexity.

---

## 2. Add integration test for the Foo flow

labels: testing

No existing coverage — the new code nearly touches it. Add a table-driven test against the Foo API boundary.

---

## 3. Document the FooConfig API

Public function with no godoc. Boy Scout violation right next to the new code.

---
`

func TestParseFollowUpsFileHappyPath(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "followups.md")
	if err := os.WriteFile(path, []byte(sampleFollowUpsFile), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := ParseFollowUpsFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 3 {
		t.Fatalf("got %d follow-ups, want 3 (%+v)", len(got), got)
	}
	want := []struct {
		title  string
		labels []string
	}{
		{"Refactor oldPkg/legacy.go", []string{"tech-debt", "refactor"}},
		{"Add integration test for the Foo flow", []string{"testing"}},
		{"Document the FooConfig API", nil},
	}
	for i, w := range want {
		if got[i].Title != w.title {
			t.Errorf("fu[%d].Title = %q, want %q", i, got[i].Title, w.title)
		}
		if len(got[i].Labels) != len(w.labels) {
			t.Errorf("fu[%d].Labels = %v, want %v", i, got[i].Labels, w.labels)
		} else {
			for j, l := range w.labels {
				if got[i].Labels[j] != l {
					t.Errorf("fu[%d].Labels[%d] = %q, want %q", i, j, got[i].Labels[j], l)
				}
			}
		}
		if got[i].Body == "" {
			t.Errorf("fu[%d].Body should not be empty", i)
		}
	}
}

func TestParseFollowUpsFileMissingFile(t *testing.T) {
	_, err := ParseFollowUpsFile("/nonexistent/path/followups.md")
	if err == nil {
		t.Error("expected error on missing file")
	}
}

func TestParseFollowUpsFileEmptyReturnsNoProposals(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "empty.md")
	os.WriteFile(path, []byte(""), 0o644)
	got, err := ParseFollowUpsFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 0 {
		t.Errorf("got %v, want no proposals", got)
	}
}

func TestParseFollowUpsFileSkipsPreamble(t *testing.T) {
	md := "# Some header\n\nSome intro paragraph.\n\n---\n\n## 1. The only proposal\n\nBody text here.\n\n---\n"
	dir := t.TempDir()
	path := filepath.Join(dir, "followups.md")
	os.WriteFile(path, []byte(md), 0o644)
	got, _ := ParseFollowUpsFile(path)
	if len(got) != 1 {
		t.Errorf("got %d, want 1 (preamble should be skipped)", len(got))
	}
	if got[0].Title != "The only proposal" {
		t.Errorf("title = %q", got[0].Title)
	}
}

func TestFileFollowUpsCallsFilerForEachProposal(t *testing.T) {
	proposals := []FollowUpIssue{
		{Title: "first", Body: "body1", Labels: []string{"a"}},
		{Title: "second", Body: "body2", Labels: []string{"b", "c"}},
	}
	calls := 0
	filer := func(title, body string, labels []string) (int, string, error) {
		calls++
		return 100 + calls, "https://github.com/o/r/issues/" + itoa(100+calls), nil
	}
	filed, err := FileFollowUps(proposals, filer)
	if err != nil {
		t.Fatal(err)
	}
	if calls != 2 {
		t.Errorf("calls = %d, want 2", calls)
	}
	if len(filed) != 2 {
		t.Errorf("filed = %d, want 2", len(filed))
	}
	if filed[0].Number != 101 || filed[1].Number != 102 {
		t.Errorf("numbers = %d/%d", filed[0].Number, filed[1].Number)
	}
}

func TestFileFollowUpsStopsOnFirstError(t *testing.T) {
	proposals := []FollowUpIssue{
		{Title: "first"},
		{Title: "second"},
		{Title: "third"},
	}
	calls := 0
	filer := func(title, body string, labels []string) (int, string, error) {
		calls++
		if calls == 2 {
			return 0, "", errors.New("rate limit")
		}
		return calls, "url", nil
	}
	filed, err := FileFollowUps(proposals, filer)
	if err == nil {
		t.Error("expected error")
	}
	if calls != 2 {
		t.Errorf("should stop at 2 calls, got %d", calls)
	}
	// The first proposal should still be in the filed slice.
	if len(filed) != 1 {
		t.Errorf("filed = %d, want 1 (the one that succeeded before the error)", len(filed))
	}
}

func TestFileFollowUpsNilFilerErrors(t *testing.T) {
	_, err := FileFollowUps([]FollowUpIssue{{Title: "x"}}, nil)
	if err == nil {
		t.Error("expected error on nil filer")
	}
}

// itoa is a local int-to-string so the test file doesn't need strconv.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [8]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return strings.TrimSpace(string(buf[i:]))
}
